### ISSUE TITLE
PDemo:  Identifiers has a "label" field that is not used

### ISSUE THREAD

**Issue by brandoncharnesky** [CareEvolution/Public#4]
PDemo:  Identifiers has a "label" field that is not used.

Patient Kevin Lee has a label passed in with his identifier.  Is this something that could/should be displayed?

**Comment by michelemottini** [comment]
In the SMART test server it seems to be a human-readable description of the identifier system - and so if available it should be displayed instead than the system URI (`urn:oid:xxxxxx`). 

I am not 100% sure that this is the correct thing to do in general because the [specs](http://www.hl7.org/implement/standards/fhir/datatypes.html#identifier) are a bit vague - they say that the label is 'Description of identifier', not 'Description of identifier system'

Our own server does not set `label` at the moment being.
